### ISSUE TITLE
추천, 검색, 카테고리 목록조회 요청 왔을 때 날짜순으로 정렬

### ISSUE THREAD

**Issue by rednada1708** [Sinclebear/makehabit_BE#29]
추천, 검색, 카테고리 목록조회 API 요청을 받았을 때
반환값이
1)  참여가능한 챌린지만 
2) 날짜순으로 정렬이 되어서 왔으면 좋겠다고 요청을 받아서 
쿼리에 startAt 기준으로 sort해서 문제를 해결할 예정입니다.

**Comment by Sinclebear** [comment]
다른 챌린지도 `시작날짜가 가까운 순` 으로 정렬되었는지 확인이 필요합니다.

**Comment by Sinclebear** [comment]
관련 내용 병합 완료 확인했습니다.
