### ISSUE TITLE
카카오 회원가입시 기본아이템 미지급 문제

### ISSUE THREAD

**Issue by rednada1708** [Sinclebear/makehabit_BE#46]
카카오로 회원 가입할 때
equippedItems와 haveItems가 빈값으로 지정되어있어
mypage화면에서 캐릭터가 보이지 않아서 수정예정입니다.

**Comment by Sinclebear** [comment]
이슈 #64 카카오톡 소셜 로그인 동작하지 않는 현상

위 이슈 수정하면서, 카카오 로그인 시 아이템 추가되는 것 확인완료. 
이슈 닫겠습니다.
