### ISSUE TITLE
각 챌린지에서 3의 배수번째 인증할 때 보상지급 관련 

### ISSUE THREAD

**Issue by rednada1708** [Sinclebear/makehabit_BE#49]
1. 고객의 동기부여
2. 프로젝트의 컨셉(작심삼일)에 따라
각 챌린지에서 3의 배수번째 인증할 때 보상 포인트를 랜덤으로 주면 어떻겠냐고 요청받았습니다.

이에 random한 숫자를 생성하여 그 숫자의 범위에 따라 포인트를 return 해주는 함수를 추가하여 활용할 예정입니다.

**Comment by Sinclebear** [comment]
3일차 보상이 확률에 따라 다르게 지급됩니다.
기존 300p
변경 300~3000p
확률표는 .env에 저장됨.
