### ISSUE TITLE
챌린지 정책 관련 수정 (당일 참여 가능, 하루 작성 가능한 게시글 수 제한)

### ISSUE THREAD

**Issue by rednada1708** [Sinclebear/makehabit_BE#59]
챌린지 정책과 관련하여 다음 두 가지 사항의 개선이 있었으면 좋겠다고 하여 
관련 API를 수정할 예정입니다.

1.  유저들의 이탈을 막기 위하여 당일에 참여와 인증이 가능하도록 API 변경

2. 포인트의 획득을 위하여 하루에 게시글을 수도 없이 생성하는 행위를 방지하기 위하여 
하루 작성 가능한 게시글 수를 제한

**Comment by Sinclebear** [comment]
status 값이 당일 인증 시 `진행 중`인 상태로 가는 케이스가 있어, 수정 예정입니다.

**Comment by Sinclebear** [comment]
Pull Request #76 에서 해결 완료.

**Comment by Sinclebear** [comment]
status 값이 두 종류가 필요합니다.
challengeStatus : 챌린지 참여 여부를 결정해주는 status 값. (진행중, 시작전, 종료)
uploadStatus : 인증샷 업로드 가능 여부를 결정해주는 status 값. (진행중, 시작전, 종료)

`modules/calcProperty.js` 에서 함수를 추가 구현하여 적용 예정입니다.

**Comment by Sinclebear** [comment]
status 값 연산 관련 함수가 두개가 되었고, 관련된 테스트 코드가 수정되었습니다.

기존 "당일 참가 가능, 당일 인증은 불가" 정책에서 "당일 참가 가능, 당일 인증 가능" 으로 변경되었을 때,
영향 범위가 생각보다 커서 위와같은 변경이 발생했습니다.

**Comment by Sinclebear** [comment]
Troubleshooting으로 작성해볼만 할 것 같습니다.
: 기획의 중요성, 요구사항이 바뀌었을 시 테스트 코드 또한 영향을 곧바로 받을 수 밖에 없음.
