### ISSUE TITLE
이메일 중복 확인이 정상 동작하지 않는 현상

### ISSUE THREAD

**Issue by Sinclebear** [Sinclebear/makehabit_BE#61]
[재현 방법]

1. 회원가입 페이지에 접근한다.
2. 아이디(이메일) 입력 란에, 이미 가입한 이메일을 입력한다.
3. `시작하기` 버튼을 눌러 가입을 시도한다.
4. 이미 가입된 이메일입니다. 메시지가 표시되고 가입되지 않는다.

[기대 결과]
이미 가입된 이메일인 경우, `사용 가능한 이메일입니다.` 대신 `사용 불가한 이메일입니다.` 메시지를 표시한다.

[참고 이미지]
![화면 캡처 2022-03-24 170836](https://user-images.githubusercontent.com/4746025/159871108-93fce276-4c6e-4618-b2d2-9e9057cd87f0.png)

**Comment by Sinclebear** [comment]
1. 우선 FE 처리 문제인지, BE 처리 문제인지 확인 필요함
2. 현재 라이브 서버에 빌드된 버전 기준, `사용 불가한 이메일입니다.` 메시지는 BE 쪽에서 보내는 것이 아닌, FE에서 자체적으로 사용한 오류 메시지임. (BE쪽 메시지는 현재 alert 에 표시된 `이미 가입된 이메일입니다.` 로 보내고 있음)

**Comment by bgg01555** [comment]
확인 결과 API 동작에는 이상이 없었고 프론트 단에서 데이터 처리 과정에 에러가 있었습니다.

**Comment by Sinclebear** [comment]
내용 확인되어 종료합니다.
