### ISSUE TITLE
랭킹 조회 API에 get요청 했을 때 equippedItems에 oid만 반환되는 현상

### ISSUE THREAD

**Issue by rednada1708** [Sinclebear/makehabit_BE#66]
랭킹조회 API로 요청이 왔을 때

백엔드에서 equippedItems에 object ID 만 담아서 보내주기 때문에
캐릭터 옷을 입힐 때 문제 발생  

개선) populate 활용해서 equippedItems에 category와 imgUrl도 함께 보내줄 예정

**Comment by bgg01555** [comment]
수정 완료했습니다.

**Comment by Sinclebear** [comment]
#67 건을 통해 수정 완료되었습니다.
- return 값 중 equippedItems에  category, itemImgUrl을 보내 FE 쪽에서 캐릭터 의상 정보를 불러올 수 있도록 변경
