### ISSUE TITLE
XSS 방어 관련 문제

### ISSUE THREAD

**Issue by rednada1708** [Sinclebear/makehabit_BE#68]
https를 도입하면 XSS 공격을 막을 수 있는 것으로 알고 있지만 
보안은 아무리 강조해도 과하지 않으니 
npm 모듈 중에 "sanitize-html"을 활용하여 
DB 저장 전에 사용자 입력값에 대한 필터링을 거친 후 
DB에 저장하도록 작업할 예정입니다.

**Comment by Sinclebear** [comment]
#73 PR로 해결 확인.
